name: New integration proposal
description: Propose a new integration for this project, either db, retriever, model_client. We highly recommend you to find a POC from the provider team to work together on this.
labels: ['[adalflow] integration']
body:
  - type: textarea
    attributes:
      label: Description & Motivation
      description: A clear and concise description of the integration proposal
      placeholder: |
        Please outline the motivation for the proposal.


  - type: textarea
    attributes:
      label: Pitch
      description: A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Provider POC
      description: If you have a POC from the provider team, please provide it here.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the integration request here.
    validations:
      required: false
