name: Suggest use cases and benchmarks
description: Propose new use cases that AdalFlow should support or benchmarks that we should compare against
labels: ["new use cases/benchmarks"]
body:
  - type: textarea
    attributes:
      label: Description & Motivation
      description: A clear and concise description of the new use case or benchmark proposal
      placeholder: |
        Please outline the motivation for the proposal.


  - type: textarea
    attributes:
      label: Pitch
      description: A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered, if any.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
