text_splitter:
  type: sentence_splitter
  chunk_size: 800
  chunk_overlap: 400
vectorizer:
  provider: openai
  model: text-embedding-3-small
  batch_size: 100
  embedding_size: 256
  encoding_format: float
retriever_type: dense_retriever
retriever:
  provider: faiss
  top_k: 1
generator:
  provider: openai
  model: gpt-3.5-turbo
  temperature: 0.3
  stream: false
